[package]
name = "distance-log"
version = "0.1.0"
authors = ["Brian Bowman <seeker14491@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
distance-util = { git = "https://github.com/Seeker14491/distance-util.git", tag = "v0.0.3", features = ["serde"] }
env_logger = "0.6.0"
failure = "0.1.2"
futures-preview = "0.3.0-alpha.17"
humantime = "1.2.0"
if_chain = "1.0.0"
indicatif = "0.11.0"
itertools = "0.8.0"
log = "0.4.5"
runtime = { git = "https://github.com/rustasync/runtime.git" }
serde = "1.0.78"
serde_derive = "1.0.78"
serde_json = "1.0.27"
steamworks = { git = "https://github.com/Seeker14491/steamworks-rs.git", tag = "v0.0.7" }
structopt = "0.2.10"
