[package]
name = "distance-log"
version = "0.1.0"
authors = ["Brian Bowman <seeker14491@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
combine = "3.5.2"
crossbeam-channel = "0.3.6"
env_logger = "0.6.0"
failure = "0.1.2"
futures = "0.1.24"
handlebars = "1.0.4"
humantime = "1.2.0"
if_chain = "0.1.3"
indicatif = "0.11.0"
jsonrpc-client-core = "0.5.0"
log = "0.4.5"
num-integer = "0.1.39"
serde = "1.0.78"
serde_derive = "1.0.78"
serde_json = "1.0.27"
structopt = "0.2.10"
take_mut = "0.2.2"
thousands = "0.1.2"
